version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: labsDB
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: konstantin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
